In [2]:
from astropy import coordinates
from astropy import units as u
import numpy as np
from astroquery.simbad import Simbad
from astroplan import Observer
from astroplan import FixedTarget
from astropy.time import Time
from astroplan.plots import plot_airmass 
import matplotlib.pyplot as plt 
from astropy.coordinates import EarthLocation
from astroplan.plots import plot_finder_image
from astroplan.plots import plot_sky

gzip was not found on your system! You should solve this issue for astroquery.eso to be at its best!
On POSIX system: make sure gzip is installed and in your path!On Windows: same for 7-zip (http://www.7-zip.org)!


In [3]:
from astroplan import download_IERS_A
download_IERS_A()

In [61]:
def observing_loc(time):
    start = Time('2020-08-02T00:22:00')
    radius_sat = 7*10**6
    radius_earth = 6.371*10**6
    G_val = 6.67*(10**(-11))
    m_earth = 5.97*(10**24)
    period = 2*np.pi*np.sqrt(radius_sat**3/(G_val*m_earth))
    half_period = period/2
    day = 86164
    delta = (time - start).value*86400
    cycles = delta // period
    remainder = delta - cycles*period
    days = delta // day
    angle = (remainder - days*day)/day
    lon_rad = 2 * np.pi * angle * u.rad
    if remainder <= half_period:
        lat = (180*(0.5 - remainder/half_period)*u.deg).to_string(unit=u.degree)
        lon_adj = (-lon_rad).to(u.deg)
    else:
        remainder -= half_period
        lat = ((180*(remainder/half_period - 0.5))*u.deg).to_string(unit=u.degree)
        lon_adj = (180*u.rad - lon_rad).to(u.deg)
    if lon_adj < -180*u.deg:
        lon_adj += 360*u.deg
    lon = lon_adj.to_string(unit=u.degree)
    SPAM = Observer(location=coordinates.EarthLocation(lat=lat, lon=lon, height=600*u.km),
               name='Smallsat Paschen Alpha Mapping',
              )
    return SPAM

In [4]:
radius = 7*10**6
G_val = 6.67*(10**(-11))
m_earth = 5.97*(10**24)
period = 2*np.pi*np.sqrt(radius**3/(G_val*m_earth))

In [5]:
now = Time.now()

In [14]:
later = Time('2020-08-02T23:00:00')

In [15]:
delta = later - now

In [16]:
delta

<TimeDelta object: scale='tai' format='jd' value=1.0666663896643518>

In [17]:
delta.value

1.0666663896643518

In [19]:
test = delta.value*86400

In [20]:
period

5831.453888647499

In [23]:
cycles = test//period
remainder = test - cycles*period
cycles, remainder

(15.0, 4688.167737287513)

In [25]:
period

5831.453888647499

In [26]:
86164*np.cos(np.pi)

-86164.0

In [62]:
yea = observing_loc(later)

In [63]:
yea

<Observer: name='Smallsat Paschen Alpha Mapping',
    location (lon, lat, el)=(-150.45398922275126 deg, 80.10065073209817 deg, 599.9999999999992 km),
    timezone=<UTC>>

In [64]:
late = Time('2020-08-31T00:23:00')

In [65]:
nah = observing_loc(late)
nah

<Observer: name='Smallsat Paschen Alpha Mapping',
    location (lon, lat, el)=(-143.33112626548976 deg, -25.144863605980913 deg, 600.0000000000008 km),
    timezone=<UTC>>

In [81]:
gal_cen = FixedTarget.from_name("Sagittarius A")
lmc = FixedTarget.from_name("LMC")
smc = FixedTarget.from_name("SMC")

In [ ]:
targets = [hd168607_target, pcyg_target, rhocas_target, polaris_target]
plot_sky(target=targets, observer=CTO, time=sunset)
plot_sky(target=targets, observer=CTO, time=onehour_after_sunset)
plot_sky(target=targets, observer=CTO, time=twohours_after_sunset)

In [ ]:
guide_style = {'marker': '*'}

plot_sky(polaris, observer, observe_time, snorth_to_east_ccw=False, style_kwargs=guide_style)
plot_sky(altair, observer, observe_time, north_to_east_ccw=False)

plt.legend(loc='center left', bbox_to_anchor=(1.25, 0.5))
plt.show()

In [67]:
observe_time = Time('2000-03-15 17:00:00')
observe_time = observe_time + np.linspace(-4, 5, 10)*u.hour
observe_time

<Time object: scale='utc' format='iso' value=['2000-03-15 13:00:00.000' '2000-03-15 14:00:00.000'
 '2000-03-15 15:00:00.000' '2000-03-15 16:00:00.000'
 '2000-03-15 17:00:00.000' '2000-03-15 18:00:00.000'
 '2000-03-15 19:00:00.000' '2000-03-15 20:00:00.000'
 '2000-03-15 21:00:00.000' '2000-03-15 22:00:00.000']>

In [82]:
spam_05_t = Time('2020-08-05T20:00:00')
spam_05 = observing_loc(spam_05_t)
spam_05.target_is_up(spam_05_t, [gal_cen, lmc, smc])

array([ True,  True,  True])

In [83]:
spam_06_t = Time('2020-08-06T20:00:00')
spam_06 = observing_loc(spam_06_t)
spam_06.target_is_up(spam_06_t, [gal_cen, lmc, smc])

array([ True,  True,  True])

In [84]:
spam_07_t = Time('2020-08-07T20:00:00')
spam_07 = observing_loc(spam_07_t)
spam_07.target_is_up(spam_07_t, [gal_cen, lmc, smc])

array([ True, False, False])

In [85]:
spam_08_t = Time('2020-08-08T20:00:00')
spam_08 = observing_loc(spam_08_t)
spam_08.target_is_up(spam_08_t, [gal_cen, lmc, smc])

array([False, False, False])